### ISSUE TITLE
Check which class names are valid

### ISSUE THREAD

**Issue by lcabrini** [Ogidi/ogidi-java-learning#10]
Check which of the following class names are valid in Java. Publish the results on the Class Name and File Name wiki page (create a section called Valid Class Names). Use a table to summarize your results. For each compilation that fails, try to explain why that class name is not valid.
1. T
2. cat
3. 4G
4. G4
5. _Basket
6. Play_Ground
7. *
8. $Account
9. Account$
10. Test.Case
11. &Car
12. Em@il
13. #Set 
14. North-West
15. 文学
16. Object
17. if
18. _
19. W<T>
    20 W[T]

**Comment by Ogidi** [comment]
Valid Class and File Names. Closes #10
