### ISSUE TITLE
Converting String to int

### ISSUE THREAD

**Issue by lcabrini** [Ogidi/ogidi-java-learning#11]
Sometimes you want to convert a String to an int. This may happen when the String holds something that is a valid integer. You are going to use a method in the Integer class for this:

```
int i = Integer.parseInt("26");
```

Beware however, the result if you do this:

```
int j = Integer.parseInt("Howdy!");
```

This will not work because Howdy cannot be converted to an integer.

The class in charge of the conversion is the Integer class, which is a class wrapper around the int primitive type. The other primitive types also have wrapper classes. Do the following:
1. create a folder called conv
2. find out all the primitive types in Java
3. For each primitive type, find it's corresping wrapper class using the Java API documentation
4. For each wrapper class, find the method that is used to convert strings into that type
5. Write a small program that demonstrates how to use the conversion method. Place the programs in the conv folder and call the class StringToX, where X is the type name. So the program to demonstrate how to convert a string to an int would be StringToInt. Write one program for each primitive type.

**Comment by Ogidi** [comment]
Converting StringToX. Closes #11
