### ISSUE TITLE
Read command-line arguments

### ISSUE THREAD

**Issue by lcabrini** [Ogidi/ogidi-java-learning#12]
You will have noticed that the main() method takes an argument called args. This will contain the command-line arguments passed in to your program. That is, if you had a java program called App and you called it like this:

```
$ java App here is some data
```

then args[0] would hold "here", args[1] would hold "is", args[2] would hold "some" and args[3] would hold "data".

The type of args is String[], that is an array of Strings. You can get the number of elements in the array by calling:

```
args.length;
```

You can use a loop to access the command-line arguments:

```
for (String a : args) {
    // do something with the string a
}
```

Of course you could also use a classical for loop:

```
for (int i = 0; i < args.length; ++i) {
    // do something with args[i]
}
```

Create a folder called args, and in this folder create a application class called App. This class should print the number of command-line arguments and list them. The following are examples of how your output should look like:

```
$ java App
Got 0 command-line arguments

$ java App foo
Got 1 command.line argument. Here it is:
1. foo

$ java App foo bar bim baz
Got 4 command-line arguments. Here they are:
1. foo
2. bar
3. bim
4. baz
```

Before you begin writing the code study the output carefully. Your program should produce _exactly_ that output based on the inputs.

**Comment by Ogidi** [comment]
Command-Line Argument. Closes #12
