### ISSUE TITLE
Write a program that prints Hello world 10 times

### ISSUE THREAD

**Issue by lcabrini** [Ogidi/ogidi-java-learning#4]
Create a variant of the hello world program that prints out the same message 10 times. Call the class MultiHello and place it in a folder called multi-hello.

**Comment by Ogidi** [comment]
Per the instruction, i created a folder in the folder on github and placed my java class in it. after compilation and running I expected that a copy of the file I compiled will be created on github after which I can then close the issue. 
My question is 'How can I close my issue after compilation and run?'

**Comment by lcabrini** [comment]
you first have to commit the file and then press the sync button.
